services:
  - type: web
    name: event-checker
    runtime: python
    plan: free
    rootDir: event-checker
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeployTrigger: commit
    healthCheckPath: /
